### ISSUE TITLE
Determine all electronic components found in the vehicle

### ISSUE THREAD

**Issue by WashingtonKK** [Arsenic-Tech/LAV1#7]
This is to enable the power team to come up with comprehensive power requirements for the entire vehicle.

**Comment by Ogweno-lab** [comment]
Who is this assigned to?

**Comment by WashingtonKK** [comment]
Byron, however he is not part of this github organization

**Comment by chepngenoh-kericho** [comment]
[lav - 1 electronic components and power.odt](https://github.com/Arsenic-Tech/LAV1/files/8302360/lav.-.1.electronic.components.and.power.odt)

**Comment by chepngenoh-kericho** [comment]
The  file above is a just a frame work of what we will need and we will be updating the list
